name: Compile Arduino Sketch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Create directory
       run: mkdir -p build
      
      - name: Compile Arduino sketches
        uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:avr:uno
          sketch-paths: |
            ./
          #Force output to a build directory
          cli-compile-flags: |
              - --output-dir
              - ./build
              - --export-binaries
      - name: Debug file locations
        run: find . -name "*.hex" -o -name "*.bin"

      - name: Upload Hex Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: uSDX-hex-output
          # Capture all .hex files from the temporary build directory
          path: ./build/
