name: Compile Arduino Sketch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install Platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr:uno

      - name: Compile Arduino sketches
        uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:avr:uno
          sketch-paths: |
            ./
          cli-compile-flags: |
            --output-dir
            ./build

      - name: Debug file locations
        run: |
          echo "Listing all files in build directory:"
          ls -R ./build
          find . -name "*.hex"

      - name: Upload Hex Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: uSDX-firmware
          # Using a wildcard ensures we grab the hex regardless of subfolders
          path: |
            ./build/*.hex
            ./build/*.bin
          if-no-files-found: error
